language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - CC=gcc CXX=g++
  - CC=gcc-5 CXX=g++-5

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

install:
  - ${CC} --version
  - pip install numpy pandas sqlalchemy
  - python -c "import numpy;print(numpy.__version__)"
  - python -c "import pandas;print(pandas.__version__)";
  - python -c "import sqlalchemy;print(sqlalchemy.__version__)";
  - pip install -e .[dev]

script:
  - py.test warp_prism
  - flake8 warp_prism

notifications:
  email: false
